### ISSUE TITLE
Setting up your local IDE, installing Git and cloning the repo

### ISSUE THREAD

**Issue by gabrielbcn** [SWE2-2020-8/NewBank#2]

**Comment by gabrielbcn** [comment]
Mine is done, please comment and the last one to close :)

**Comment by NaomiOkiddy** [comment]
Cloned and set up!

**Comment by saraalkuwari1** [comment]
Done!

**Comment by sj702** [comment]
<img width="1440" alt="Screenshot 2020-07-10 at 15 09 05" src="https://user-images.githubusercontent.com/58032491/87163488-5a6f3100-c2bf-11ea-8d94-86ed55239738.png">
Struggling to install GitHub I've installed from the website via homebrew and believe that the file I downloaded is open

**Comment by gabrielbcn** [comment]
If you have brew, `brew install git` will do the trick, also `brew cask install visual-studio-code`. If it cannot find it then `brew tap caskroom/cask`. It should work :)

**Comment by gabrielbcn** [comment]
I also recommend `brew cask install iterm2`

**Comment by sj702** [comment]
Thanks Gabriel I'll give visual-studio-code a go now!

**Comment by sj702** [comment]
<img width="1440" alt="Screenshot 2020-07-10 at 18 09 36" src="https://user-images.githubusercontent.com/58032491/87180480-84811d00-c2d8-11ea-8dd2-ae95f2d1598f.png">
believe it's done!

**Comment by NaomiOkiddy** [comment]
Everyone has gotten set up!
