### ISSUE TITLE
Meeting Saturday 11th

### ISSUE THREAD

**Issue by gabrielbcn** [SWE2-2020-8/NewBank#3]
Same time slot and same link

[Join Zoom Meeting](https://us04web.zoom.us/j/72912750201?pwd=R3NPYlEzMHN4c0hRY014WC9KQTVOUT09)

Meeting ID: 729 1275 0201
Password: 6TLJpC

Please confirm by commenting.

**Comment by saraalkuwari1** [comment]
Confirmed

**Comment by NaomiOkiddy** [comment]
Sounds good

**Comment by NaomiOkiddy** [comment]
### Meeting Notes

1. Getting everyone up to speed
        - Running locally
        - Running remotely
        - Figuring out where everyone is
        - Going over what was done in last week's sprint

1. Selection of tasks for next week's sprint

1. Selection of roles
     - New Scrum Master = @NaomiOkiddy 
     - New Project Owner = @saraalkuwari1 
     - New Scrum Team Members = @gabrielbcn , @sj702 

1. Getting everyone's individual Report (Post answers on [wiki](https://github.com/SWE2-2020-8/NewBank.wiki.git))
