### ISSUE TITLE
Change successful login message to SUCCESS

### ISSUE THREAD

**Issue by gabrielbcn** [SWE2-2020-8/NewBank#39]
To have some consistency for the client. Please change ASAP.

Anything is successful -> Reply starts with **SUCCESS**
Non successful -> **FAIL**

You can add comments such as  (type OPTIONS for help) after the SUCCESS or FAIL keyword

**Comment by saraalkuwari1** [comment]
done

**Comment by gabrielbcn** [comment]
Now we have a message in two lines, which is not compliant to what is requested above, please correct @saraalkuwari1 

`SUCCESS
 Log In Successful (type OPTIONS for help)`

**Comment by saraalkuwari1** [comment]
updated

**Comment by gabrielbcn** [comment]
Whenever available, can we discuss this? It's important to have a clear understanding of what we're doing. 

This is what we're building (very similar)

![Architecture-of-a-Rich-Client-Application](https://user-images.githubusercontent.com/45199871/88023474-6f2bae80-cb74-11ea-8321-09f41edc4029.png)

**Comment by gabrielbcn** [comment]
This is what the server is replying now:
```
➜  ~ socat - TCP4:swe2-2020-8.southeastasia.azurecontainer.io:80
Enter Username
Admin
Enter Password
1234
Checking Details...
SUCCESS
Log In Successful (type OPTIONS for help)
```
Please make it be:
```
➜  ~ socat - TCP4:swe2-2020-8.southeastasia.azurecontainer.io:80
Enter Username
Admin
Enter Password
1234
SUCCESS (type OPTIONS for help)
```

**Comment by gabrielbcn** [comment]
In the right direction but not complete, please review the [requirements](https://github.com/SWE2-2020-8/NewBank/wiki/User-Stories-and-Requirements)

**Comment by gabrielbcn** [comment]
Closed with thanks
