### ISSUE TITLE
Review requirements and user stories

### ISSUE THREAD

**Issue by saraalkuwari1** [SWE2-2020-8/NewBank#50]

**Comment by NaomiOkiddy** [comment]
- Create the User Story for PAYINTEREST @saraalkuwari1 @NaomiOkiddy
- We all review the wiki at the end of the week so that we're sure that the user stories and requirements reflect what we have done @NaomiOkiddy @saraalkuwari1 @gabrielbcn

**Comment by gabrielbcn** [comment]
Done from my side, reviewed and added few

**Comment by NaomiOkiddy** [comment]
Reviewed, I personally didn't see anything else to add
