### ISSUE TITLE
Client should support 

### ISSUE THREAD

**Issue by saraalkuwari1** [SWE2-2020-8/NewBank#55]
- [x] account details

- [x]  deposit option

- [ ] withdraw option

- [x] move option

- [ ]  transfer option

**Comment by gabrielbcn** [comment]
Account details done

**Comment by gabrielbcn** [comment]
Client can now create account

**Comment by gabrielbcn** [comment]
Client can now deposit money

**Comment by gabrielbcn** [comment]
Client can now withdraw money, @NaomiOkiddy @saraalkuwari1 kindly implement in server so I can test it (done in branch client)

**Comment by gabrielbcn** [comment]
Move done in pull request

**Comment by gabrielbcn** [comment]
Transfer needs to be changed in the server so that the origin account is specified. Otherwise it would be weird to implement in the client as maybe an account different than the one selected is changing. See issue #58
