### ISSUE TITLE
PAY method doesn't specify which account the money is coming from

### ISSUE THREAD

**Issue by gabrielbcn** [SWE2-2020-8/NewBank#58]
So how does it know? It should must decide which account to take money from. 

What about the account it is going to? Wasn't that asked to the originator? What were your assumptions?

@NaomiOkiddy @saraalkuwari1

**Comment by saraalkuwari1** [comment]
It takes money from the main account of the client, since this is what banks do.

**Comment by gabrielbcn** [comment]
There's no main account. We never defined that in the specs or in the user stories.

If there was a main we would need to mark it with a specific field and we would need the functionality for the customer to choose and change.

It's either that or making the customer select one.

I challenge what you said before: when you pay money to a third party is it really your bank choosing the account the money comes from for you or do you choose which account you're taking the money from?

For me the user story is clearly about a customer transferring the money from the account he chooses, not from the account the bank chooses.

**Comment by gabrielbcn** [comment]
Corrections to be done, see requirements too. Development must be done in line with User Stories and Requirements, never in a vacuum. New PR must be previously tested.

**Comment by gabrielbcn** [comment]
[Ongoing discussions on where the payment is going to](https://github.com/SWE2-2020-8/NewBank/pull/67#discussion_r464006520)
