### ISSUE TITLE
Code Review and Verification

### ISSUE THREAD

**Issue by NaomiOkiddy** [SWE2-2020-8/NewBank#72]
- Work ends in a PR, code gets reviewed and commented, new corrections pushed, closing the PR closes the issue. @gabrielbcn
- We verify all the functionalities end to end. If bugs are found, open an issue as a bug @NaomiOkiddy @saraalkuwari1 @gabrielbcn

**Comment by gabrielbcn** [comment]
Done from my side, refactored few things

**Comment by NaomiOkiddy** [comment]
Tested it up against the user stories, worked fine for me

**Comment by saraalkuwari1** [comment]
Works flawlessly with me.
